name: CI
on:
  push:
    tags-ignore:
      - 'v*.*.*'
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: antwika/actions/packages/ci@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          sonar-token: ${{ secrets.SONAR_TOKEN }}
