name: CI
on:
  push:
    branches:
      - "main"
    tags-ignore:
      - 'v0.0.4'
  pull_request:
    branches:
      - "**"
    tags-ignore:
      - 'v0.0.4'
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: antwika/actions/packages/ci@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          sonar-token: ${{ secrets.SONAR_TOKEN }}
