name: Publish
on:
  push:
    branches: [main]
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Branch name
        run: echo running on branch ${GITHUB_REF##*/}
      - name: Checked run
        if: startsWith(github.ref, 'refs/tags/v')
        run: echo RAN